name: Auto Release Datapack

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create resourcepack zip from rp folder
        run: |
          cd rp
          zip -r "../Better-Ghast-Harness-RP-${{ github.ref_name }}.zip" .

      - name: Create datapack zip from src folder
        run: |
          cd src
          zip -r "../Better-Ghast-Harness-DP-${{ github.ref_name }}.zip" .

      - name: Extract latest changelog entry
        id: changelog
        run: |
          awk '/^## /{if (NR>1) exit} {print}' changelog.md > latest_changelog.txt
          {
            echo "body<<EOF"
            cat latest_changelog.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release & attach zip
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.body }}
          files: |
            "Better-Ghast-Harness-DP-${{ github.ref_name }}.zip"
            "Better-Ghast-Harness-RP-${{ github.ref_name }}.zip"
          name: "Better Ghast Harness ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
